### ISSUE TITLE
ExtUtils-Install

### ISSUE THREAD

**Issue by toddr** [toddr/perl-modernization#31]
Jim has a stab at fixing strictness here. https://github.com/Perl-Toolchain-Gang/ExtUtils-Install/pull/23

**Comment by toddr** [comment]
This would also fix some of the strictness issues - https://github.com/Perl-Toolchain-Gang/ExtUtils-Install/pull/25

**Comment by haarg** [comment]
Incorrect ticket name?

**Comment by toddr** [comment]
Uploaded to CPAN. I'm working on a PR for perl5

**Comment by toddr** [comment]
https://github.com/Perl/perl5/pull/18141

**Comment by toddr** [comment]
merged
